-- MyReal Supabase schema
create table if not exists public.myreal_meta (
  token text primary key,
  image_key text not null,
  created_at timestamptz not null,
  expires_at timestamptz not null,
  palette jsonb not null,
  source text not null
);

create table if not exists public.myreal_feedback (
  id bigint generated by default as identity primary key,
  score int not null check (score between 1 and 5),
  comment text,
  created_at timestamptz not null default now(),
  token text
);

create table if not exists public.myreal_runs (
  id bigint generated by default as identity primary key,
  success boolean not null,
  duration_ms int,
  created_at timestamptz not null default now()
);
